let dataCar = [{
    "id": 1,
    "name": "Toyota",
    "color": "Yellow",
    "year": 1995,
    "cc": 4152,
    "price": "$5.47"
  }, {
    "id": 2,
    "name": "Chrysler",
    "color": "Maroon",
    "year": 1997,
    "cc": 3268,
    "price": "$5.36"
  }, {
    "id": 3,
    "name": "Pontiac",
    "color": "Maroon",
    "year": 1967,
    "cc": 1349,
    "price": "$5.02"
  }, {
    "id": 4,
    "name": "Geo",
    "color": "Green",
    "year": 1997,
    "cc": 3400,
    "price": "$7.01"
  }, {
    "id": 5,
    "name": "Mercury",
    "color": "Blue",
    "year": 1994,
    "cc": 2280,
    "price": "$6.97"
  }, {
    "id": 6,
    "name": "Chevrolet",
    "color": "Aquamarine",
    "year": 2001,
    "cc": 1055,
    "price": "$7.70"
  }, {
    "id": 7,
    "name": "Honda",
    "color": "Red",
    "year": 2006,
    "cc": 4808,
    "price": "$5.68"
  }, {
    "id": 8,
    "name": "Ford",
    "color": "Turquoise",
    "year": 2004,
    "cc": 3420,
    "price": "$6.16"
  }, {
    "id": 9,
    "name": "Toyota",
    "color": "Crimson",
    "year": 1993,
    "cc": 3743,
    "price": "$8.02"
  }, {
    "id": 10,
    "name": "Buick",
    "color": "Green",
    "year": 1984,
    "cc": 1655,
    "price": "$5.78"
  }]

  module.exports = dataCar